version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_DB_NAME: "nest"
      DB_HOST: "nest"
      #NODE_TLS_REJECT_UNAUTHORIZED: 0
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
